### ISSUE TITLE
TriggerMode on AH501

### ISSUE THREAD

**Issue by xiaoqiangwang** [epics-modules/quadEM#14]
On AH501B devices there is only one signal input for trigger. From its function, it acts as a gate signal. Probably that is why in file [AH501.template](https://github.com/epics-modules/quadEM/blob/master/quadEMApp/Db/AH501.template#L30), the TriggerMode has the value `4` "ext. gate". 

But in the [drvAHxxx.cpp](https://github.com/epics-modules/quadEM/blob/master/quadEMApp/src/drvAHxxx.cpp#L495), it only checks for `QETriggerModeExtTrigger`. This would prevent the trigger mode to work.

The fix could be changing either the template to `2` "ext. trig." or the driver to
``if (triggerMode == QETriggerModeExtTrigger || triggerMode == QETriggerModeExtGate)``. Locally I have changed the template to get it work.

**Comment by MarkRivers** [comment]
@xiaoqiangwang thanks for finding that problem.

I have fixed the code and pushed to Github.

**Comment by MarkRivers** [comment]
Closed via 61842a83dbef04786efcf3d1ccbc72fbd38f2534.
