### ISSUE TITLE
Stop/Start acquisition fails under "ext. trigger" mode

### ISSUE THREAD

**Issue by NilsonPereira** [epics-modules/quadEM#17]
**Device:**
CAENels - TetrAMM

**Issue:**
Acquisition fails to restart under external trigger mode.

**Expected behaviour:**
Under external trigger mode, the device should start and stop acquisition at any time and also allow changes in the averaging time during acquisition

**Actual behaviour:**
Once acquisition has been started under external trigger mode, if fails to restart once stopped. It captures only the first trigger and then halts.
Sometimes, it outputs the following console error message: "drvTetrAMM::readThread Extra trigger end, numTrigStarts=0, numTrigsEnds=1"
An attempt to correct the issue by changing the order of commands (first NAQ and then TRG) makes the device fail to function under ext. trigger at all. 

**Build Environment**
Architecture: linux-x86_64
Epics Base Version: 3.15.5
Dependent Module Versions: 
asyn-R4-33
quadEM-R9-1
areaDetector-R3-3-2
busy-R1.6.1
ipac-2.15
ipUnidig-R2-11
seq-R2.2.4
autosave-R5.7.1
sscan-R2.10
calc-R3.6.1
devIocStats-3-1-15

**Comment by MarkRivers** [comment]
Hi Nilson, 

I need to know more about your configuration.

Please tell me the values of the following PVs:
AcquireMode
ValuesPerRead
AveragingTime
ReadFormat
NumChannels

What is the period between trigger pulses that you are sending?

I have a system set up for testing now.

I am using the following parameters:
AcquireMode=Continuous
ValuesPerRead=5
AveragingTime=0.1
ReadFormat=Binary
NumChannels=4

It works fine for me with those settings.   When I send a trigger it averages for averaging time and produces a reading.  I can change the averaging time and start and stop acquisition and it all seems to work with no problems.

This is a screen shot of my screen.
![image](https://user-images.githubusercontent.com/6115534/46562228-b6be4900-c8c0-11e8-9201-00b7e48089a5.png)

**Comment by MarkRivers** [comment]
Perhaps the problem is a firmware issue.  What firmware version are you running?  I am running 2.9.11.  There were some firmware changes made that affected the trigger logic.

**Comment by NilsonPereira** [comment]
The problem was related to the firmware version. The issue was resolved when upgrading from firmware 2.0.09 to 2.9.11 as recommended. 
This issue is now closed.
